import { Company, Tickets } from './DummyModel'

import lunch_img from '../assets/CompanyInformation/lunch-img.svg'
import waitlist_img from '../assets/CompanyInformation/waitlist-img.svg'
import { UserModel } from './UserModel'

const dummyCompanies: Company[] = [
    {
        name: "Alstom Transport AB",
        image: "#2BDBA0",
        id: 0,
        tags: ["workshop", "mingle"],
        fieldOfStudy:["Computer Science and Engineering", "Electrical Engineering", "Engineering Physics", "Environmental Engineering", "Industrial Management", "Information and Communication Technology", "Mechanical Engineering"],
        coordinators: [{ name: "Anna Mared", mail: "anna.mared@alstomgroup.com", img: "null" }],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Bachelor Thesis", "Part Time Job", "Summer Job", "Trainee"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 12,
        starred: true,
        collectedTickets: 0,
        aboutUs: "From high-speed trains, metros, monorails, trams, to turnkey systems, services, infrastructure, signaling and digital mobility, Alstom offers its diverse customers the broadest portfolio in the industry. 150,000 vehicles in commercial service worldwide attest to the company’s proven expertise in project management, innovation, design and technology. In 2021, the company was included in the Dow Jones Sustainability Indices, World and Europe, for the 11th consecutive time."
    },
    {
        name: "Epiroc",
        image: "#DB2B2B",
        id: 1,
        tags: ["workshop", "mingle"],
        fieldOfStudy:["Computer Science and Engineering", "Electrical Engineering", "Engineering Physics", "Industrial Management", "Information and Communication Technology", "Material Science and Engineering", "Mathematics", "Mechanical Engineering", "Technology and Management"],
        coordinators: [{ name: "Klara Petersen", mail: "klara.petersen@epiroc.com", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Bachelor Thesis", "Part Time Job", "Summer Job"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Gröten, Nymble",
        stall: 30,
        starred: true,
        collectedTickets: 10,
        aboutUs: "Epiroc is a vital part of a sustainable society and a global productivity partner for mining and infrastructure customers. We develop and provide innovative and safe equipment, such as drill rigs, rock excavation and construction equipment and tools for surface and underground applications. We also offer world-class service and other aftermarket support as well as solutions for automation, digitalization and electrification. Epiroc is based in Stockholm, Sweden and has more than 15 500 passionate employees supporting and collaborating with customers in more than 150 countries."
    },
    {
        name: "FMV Försvarets materielverk",
        image: "#FFE6E6",
        id: 2,
        tags: ["workshop", "mingle"],
        fieldOfStudy: ["Biotechnology", "Chemical Science and Engineering", "Computer Science and Engineering", "Electrical Engineering", "Engineering Physics", "Environmental Engineering", "Industrial Management", "Information and Communication Technology", "Material Science and Engineering", "Mathematics", "Mechanical Engineering", "Medical Engineering", "Technology and Economics", "Technology and Health", "Technology and Learning", "Technology and Management", "The Built Environment"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "KTH Bibliotek",
        stall: 92,
        starred: false,
        collectedTickets: 0,
        aboutUs: "The Swedish Defence Materiel Administration, FMV, is a governmental agency acting under the Ministry of Defence. We make sure the Swedish Armed Forces have the equipment and logistic services they need to execute their mission. That is our contribution to a stronger defense."
    },
    {
        name: "Gartner",
        image: "#0F1322",
        id: 3,
        tags: ["workshop", "mingle"],
        fieldOfStudy: ["Technology and Economics", "Technology and Health", "Technology and Learning", "Technology and Management", "Information and Communication Technology"],
        coordinators: [{ name: "Stephanie Shull", mail: "stephanie.shull@gartner.com", img: "null" }],
        offerings: ["Full Time Job",  "Internship"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Kårbokhandeln",
        stall: 145,
        starred: true,
        collectedTickets: 0,
        aboutUs: "Founded in 1979, we are the leading research and advisory company. We’ve expanded well beyond our flagship technology research to provide senior leaders across the enterprise with the indispensable business insights, advice and tools they need to achieve their mission-critical priorities and build the organizations of tomorrow. Together with our clients, we fuel the future of business so that a more successful world takes shape. Our clients turn to us for indispensable management and technology insights, advice and tools, delivered through our three lines of business."
    },
    {
        name: "Volvo Automotive V",
        image: "#E6FFF7",
        id: 3,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: true,
        collectedTickets: 0,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    },
    {
        name: "Volvo Automotive VI",
        image: "#FFE6E6",
        id: 3,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: true,
        collectedTickets: 0,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    }, {
        name: "Volvo Automotive VII",
        image: "#2BDBA0",
        id: 0,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: true,
        collectedTickets: 0,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    },
    {
        name: "Volvo Automotive VIII",
        image: "#999999",
        id: 1,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: true,
        collectedTickets: 10,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    },
    {
        name: "Volvo Automotive IX",
        image: "#FFF5E6",
        id: 2,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: false,
        collectedTickets: 0,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    },
    {
        name: "Volvo Automotive X",
        image: "#0F1322",
        id: 3,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: true,
        collectedTickets: 0,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    },
    {
        name: "Volvo Automotive XI",
        image: "#E6FFF7",
        id: 3,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: true,
        collectedTickets: 0,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    },
    {
        name: "Volvo Automotive XII",
        image: "#F2F2F2",
        id: 3,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: true,
        collectedTickets: 0,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    },
    {
        name: "Volvo Automotive XIII",
        image: "#2BDBA0",
        id: 3,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: true,
        collectedTickets: 0,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    },
    {
        name: "Volvo Automotive XIV",
        image: "#F9A444",
        id: 3,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: true,
        collectedTickets: 0,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    },
    {
        name: "Volvo Automotive XV",
        image: "#333333",
        id: 3,
        tags: ["workshop", "mingle"],
        coordinators: [{ name: "Nina", mail: "nina@mail.se", img: "null" }, { name: "Malin", mail: "malin@mail.se", img: "null" }],
        offerings: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        askAbout: ["Full Time Job", "Masters Thesis", "Internship", "Green jobs"],
        extraInfo: [{ info: "Lunch Provided", img: lunch_img }, { info: "Waitlist Available", img: waitlist_img }],
        location: "Nya Matsalen, Nymble",
        stall: 50,
        starred: true,
        collectedTickets: 0,
        aboutUs: "Are you worried about getting stuck in the “I need experience to get a job but to get a job I need experience” paradox? Don’t worry! With foodora's Aspiring Leadership Program you will get a flexible part time job, valuable knowledge in leadership/management and hands on leadership experience! This is the perfect opportunity if you want to boost your resumé and at the same time earn some extra money! Who are we?: We’re foodorians, a driven and happy gang of food lovers eager to create the last mile delivery service of the future! Our core values help concretize what we’re aiming for: We dare, We get it done & We’re equally pink. We’re people from all backgrounds, with different experiences, opinions and ideas. This is something we value highly, since we fully believe that diversity is what builds our culture and success."
    }
    
]

const dummyTickets: Tickets[] = [{ companyId: 0, nrOfTickets: 30 }, { companyId: 0, nrOfTickets: 30 }, { companyId: 0, nrOfTickets: 0 }, { companyId: 0, nrOfTickets: 30 }]

export { dummyCompanies, dummyTickets }